on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target_type:
          - server
        test:
          - true
          - false

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m ${{ matrix.test == true && 'debug' || 'release' }} -p windows -v -y --target_type=${{ matrix.target_type }} --test=${{ matrix.test }}

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}${{ matrix.test == true && '-test' || '' }}-windows-x64-${{ github.sha }}
          path: |
            bin/
